import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Research interest topics (migrated from Jekyll _research/)
const research = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/research' }),
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    order: z.number(),
    tags: z.array(z.enum(['geo', 'biz', 'ai', 'finance'])),
    projects: z.array(
      z.object({
        title: z.string(),
        abstract: z.string(),
        image: z.string().optional(),
        pdf: z.string().optional(),
        github: z.string().optional(),
        link: z.string().optional(),
      })
    ),
  }),
});

// Tier-1 case studies (authored in Phase 2)
const cases = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/cases' }),
  schema: z.object({
    title: z.string(),
    tagline: z.string(),
    year: z.string(),
    role: z.enum(['personal', 'lead', 'team']),
    tags: z.array(z.enum(['geo', 'biz', 'ai', 'finance'])),
    repoUrl: z.string().url(),
    org: z.string().optional(),
    featured: z.boolean().default(false),
    order: z.number(),
    metrics: z.array(z.object({ label: z.string(), value: z.string() })),
  }),
});

// Chinese mirrors (generated by scripts/translate.mjs, human-reviewed)
const researchZh = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/research-zh' }),
  schema: research.schema,
});
const casesZh = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/cases-zh' }),
  schema: cases.schema,
});

export const collections = { research, cases, researchZh, casesZh };
